/* eslint-disable */
// @ts-nocheck
// Generated by scripts/drumLooper.generator.ts

export interface DrumKitManifestItem {
  group: string;
  id: string;
  kit: string;
  name: string;
  path: string;
}

export interface DrumKitManifest {
  id: string;
  name: string;
  samples: DrumKitManifestItem[];
  starterSamples: DrumKitManifestItem[];
}

export const drumKits: DrumKitManifest[] = [
  {
    "id": "lofi-drum-kit-vol-2",
    "name": "LoFi Drum Kit Vol. 2",
    "samples": [
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-1-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (1)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (1).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-10-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (10)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (10).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-11-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (11)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (11).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-12-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (12)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (12).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-13-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (13)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (13).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-14-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (14)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (14).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-15-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (15)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (15).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-16-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (16)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (16).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-17-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (17)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (17).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-18-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (18)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (18).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-19-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (19)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (19).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-2-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (2)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (2).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-20-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (20)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (20).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-21-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (21)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (21).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-22-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (22)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (22).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-23-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (23)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (23).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-24-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (24)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (24).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-25-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (25)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (25).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-26-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (26)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (26).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-3-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (3)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (3).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-4-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (4)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (4).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-5-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (5)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (5).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-6-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (6)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (6).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-7-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (7)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (7).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-8-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (8)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (8).wav"
      },
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-9-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (9)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (9).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-1-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (1)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (1).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-10-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (10)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (10).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-11-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (11)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (11).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-12-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (12)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (12).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-13-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (13)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (13).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-14-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (14)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (14).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-15-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (15)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (15).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-16-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (16)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (16).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-17-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (17)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (17).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-2-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (2)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (2).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-3-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (3)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (3).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-4-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (4)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (4).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-5-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (5)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (5).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-6-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (6)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (6).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-7-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (7)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (7).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-8-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (8)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (8).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-9-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (9)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (9).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-1-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (1)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (1).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-10-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (10)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (10).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-11-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (11)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (11).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-12-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (12)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (12).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-13-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (13)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (13).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-14-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (14)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (14).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-15-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (15)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (15).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-16-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (16)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (16).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-17-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (17)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (17).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-2-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (2)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (2).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-3-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (3)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (3).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-4-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (4)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (4).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-5-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (5)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (5).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-6-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (6)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (6).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-7-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (7)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (7).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-8-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (8)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (8).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-9-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (9)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (9).wav"
      },
      {
        "group": "Noise",
        "id": "lofi-drum-kit-vol-2-noise-lofi-noise-1-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Noise (1)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Noise/lofi noise (1).wav"
      },
      {
        "group": "Noise",
        "id": "lofi-drum-kit-vol-2-noise-lofi-noise-2-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Noise (2)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Noise/lofi noise (2).wav"
      },
      {
        "group": "Noise",
        "id": "lofi-drum-kit-vol-2-noise-lofi-noise-3-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Noise (3)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Noise/lofi noise (3).wav"
      },
      {
        "group": "Noise",
        "id": "lofi-drum-kit-vol-2-noise-lofi-noise-4-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Noise (4)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Noise/lofi noise (4).wav"
      },
      {
        "group": "Noise",
        "id": "lofi-drum-kit-vol-2-noise-lofi-noise-5-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Noise (5)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Noise/lofi noise (5).wav"
      },
      {
        "group": "Noise",
        "id": "lofi-drum-kit-vol-2-noise-lofi-noise-6-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Noise (6)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Noise/lofi noise (6).wav"
      },
      {
        "group": "Noise",
        "id": "lofi-drum-kit-vol-2-noise-lofi-noise-7-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Noise (7)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Noise/lofi noise (7).wav"
      },
      {
        "group": "Noise",
        "id": "lofi-drum-kit-vol-2-noise-lofi-noise-8-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Noise (8)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Noise/lofi noise (8).wav"
      },
      {
        "group": "Noise",
        "id": "lofi-drum-kit-vol-2-noise-lofi-noise-9-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Noise (9)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Noise/lofi noise (9).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-1-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (1)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (1).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-10-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (10)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (10).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-11-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (11)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (11).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-12-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (12)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (12).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-13-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (13)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (13).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-14-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (14)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (14).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-15-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (15)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (15).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-16-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (16)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (16).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-17-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (17)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (17).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-18-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (18)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (18).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-19-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (19)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (19).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-2-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (2)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (2).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-20-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (20)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (20).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-21-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (21)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (21).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-3-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (3)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (3).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-4-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (4)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (4).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-5-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (5)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (5).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-6-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (6)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (6).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-7-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (7)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (7).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-8-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (8)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (8).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-9-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (9)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (9).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-1-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (1)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (1).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-10-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (10)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (10).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-11-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (11)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (11).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-12-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (12)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (12).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-13-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (13)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (13).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-14-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (14)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (14).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-15-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (15)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (15).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-16-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (16)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (16).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-17-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (17)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (17).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-18-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (18)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (18).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-2-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (2)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (2).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-3-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (3)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (3).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-4-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (4)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (4).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-5-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (5)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (5).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-6-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (6)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (6).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-7-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (7)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (7).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-8-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (8)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (8).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-9-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (9)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (9).wav"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-a-vinyljazzguitar-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "A VinylJazzGuitar",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/A_VinylJazzGuitar.wav"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-ahmad-jamal-soul-girl-mp3",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Ahmad Jamal Soul Girl",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/Ahmad Jamal - Soul Girl.mp3"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-both-hands-free-phobos-mp3",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Both Hands Free Phobos",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/Both Hands Free - Phobos.mp3"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-c418-subwoofer-lullaby-minecraft-volume-alpha-mp3",
        "kit": "lofi-drum-kit-vol-2",
        "name": "C418 Subwoofer Lullaby Minecraft Volume Alpha",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/C418 - Subwoofer Lullaby - Minecraft Volume Alpha.mp3"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-claude-larson-memory-image-mp3",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Claude Larson Memory Image",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/Claude Larson - Memory Image.mp3"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-eden-of-the-east-ost-18-mitasareta-koritsu-mp3",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Eden Of The East OST 18 Mitasareta Koritsu",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/Eden of the East OST - 18 Mitasareta Koritsu.mp3"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-invention-ebb-flo-mp3",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Invention Ebb Flo",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/invention_ - ebb__flo.mp3"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-kenny-pore-walking-with-you-mp3",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Kenny Pore Walking With You",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/Kenny Pore - Walking With You.mp3"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-krzysztof-komeda-making-love-in-the-apartment-mp3",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Krzysztof Komeda Making Love In The Apartment",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/krzysztof komeda - Making love in the Apartment.mp3"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-lil-peep-pad-1-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lil Peep Pad (1)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/lil peep pad (1).wav"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-lil-peep-pad-5-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lil Peep Pad (5)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/lil peep pad (5).wav"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-lofi-loop-130-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "LoFi Loop 130",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/LoFi Loop 130.wav"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-rolf-k-hn-manhattan-skyline-ii-mp3",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Rolf Kühn Manhattan Skyline II",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/Rolf Kühn - Manhattan Skyline II.mp3"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-sophie-lowe-a-runner-mp3",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Sophie Lowe A Runner",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/Sophie Lowe - A Runner.mp3"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-sweet-charles-strangers-in-the-night-mp3",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Sweet Charles Strangers In The Night",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/Sweet Charles - Strangers in the night.mp3"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-toyohirakumin-mp3",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Toyohirakumin ダンサー",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/Toyohirakumin - ダンサー.mp3"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-tsuyoshi-yamamoto-i-am-fool-to-want-you-mp3",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Tsuyoshi Yamamoto I Am Fool To Want You",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/Tsuyoshi Yamamoto - I_am fool to want you.mp3"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-untitled-project-2019-feb-09-5-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Untitled Project 2019 Feb 09 5",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/Untitled project - 2019-Feb-09_5.wav"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-mp3",
        "kit": "lofi-drum-kit-vol-2",
        "name": "パイプ 優しいシャワー",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/パイプ - 優しいシャワー.mp3"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-irene-mp3",
        "kit": "lofi-drum-kit-vol-2",
        "name": "安部恭弘 アイリーン (Irene)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/安部恭弘 - アイリーン (Irene).mp3"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-1-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (1)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (1).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-10-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (10)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (10).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-11-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (11)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (11).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-12-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (12)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (12).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-13-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (13)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (13).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-14-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (14)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (14).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-15-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (15)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (15).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-16-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (16)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (16).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-17-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (17)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (17).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-18-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (18)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (18).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-19-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (19)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (19).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-2-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (2)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (2).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-20-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (20)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (20).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-21-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (21)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (21).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-3-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (3)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (3).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-4-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (4)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (4).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-5-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (5)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (5).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-6-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (6)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (6).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-7-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (7)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (7).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-8-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (8)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (8).wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-9-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (9)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (9).wav"
      }
    ],
    "starterSamples": [
      {
        "group": "Closed Hats",
        "id": "lofi-drum-kit-vol-2-closed-hats-lofi-closed-hat-1-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Closed Hat (1)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Closed Hats/lofi closed hat (1).wav"
      },
      {
        "group": "Drum Loops",
        "id": "lofi-drum-kit-vol-2-drum-loops-lofi-drum-loop-1-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Drum Loop (1)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Drum Loops/lofi drum loop (1).wav"
      },
      {
        "group": "Kicks",
        "id": "lofi-drum-kit-vol-2-kicks-lofi-kick-1-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Kick (1)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Kicks/lofi kick (1).wav"
      },
      {
        "group": "Noise",
        "id": "lofi-drum-kit-vol-2-noise-lofi-noise-1-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Noise (1)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Noise/lofi noise (1).wav"
      },
      {
        "group": "Open Hats",
        "id": "lofi-drum-kit-vol-2-open-hats-lofi-open-hat-1-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Open Hat (1)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Open Hats/lofi open hat (1).wav"
      },
      {
        "group": "Percs",
        "id": "lofi-drum-kit-vol-2-percs-lofi-perc-1-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Perc (1)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Percs/lofi perc (1).wav"
      },
      {
        "group": "Samples & Random Chops",
        "id": "lofi-drum-kit-vol-2-samples-random-chops-a-vinyljazzguitar-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "A VinylJazzGuitar",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Samples & Random Chops/A_VinylJazzGuitar.wav"
      },
      {
        "group": "Snares",
        "id": "lofi-drum-kit-vol-2-snares-lofi-snare-1-wav",
        "kit": "lofi-drum-kit-vol-2",
        "name": "Lofi Snare (1)",
        "path": "/drum-looper/LoFi Drum Kit Vol. 2/Snares/lofi snare (1).wav"
      }
    ]
  }
];
