/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BinauralBeatsRouteImport } from './routes/binaural-beats'
import { Route as DrumLooperRouteImport } from './routes/drum-looper'
import { Route as MetronomeRouteImport } from './routes/metronome'
import { Route as TunerRouteImport } from './routes/tuner'
import { Route as WorshipPadRouteImport } from './routes/worship-pad'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BinauralBeatsRoute = BinauralBeatsRouteImport.update({
  id: '/binaural-beats',
  path: '/binaural-beats',
  getParentRoute: () => rootRouteImport,
} as any)
const DrumLooperRoute = DrumLooperRouteImport.update({
  id: '/drum-looper',
  path: '/drum-looper',
  getParentRoute: () => rootRouteImport,
} as any)
const MetronomeRoute = MetronomeRouteImport.update({
  id: '/metronome',
  path: '/metronome',
  getParentRoute: () => rootRouteImport,
} as any)
const TunerRoute = TunerRouteImport.update({
  id: '/tuner',
  path: '/tuner',
  getParentRoute: () => rootRouteImport,
} as any)
const WorshipPadRoute = WorshipPadRouteImport.update({
  id: '/worship-pad',
  path: '/worship-pad',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/binaural-beats': typeof BinauralBeatsRoute
  '/drum-looper': typeof DrumLooperRoute
  '/metronome': typeof MetronomeRoute
  '/tuner': typeof TunerRoute
  '/worship-pad': typeof WorshipPadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/binaural-beats': typeof BinauralBeatsRoute
  '/drum-looper': typeof DrumLooperRoute
  '/metronome': typeof MetronomeRoute
  '/tuner': typeof TunerRoute
  '/worship-pad': typeof WorshipPadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/binaural-beats': typeof BinauralBeatsRoute
  '/drum-looper': typeof DrumLooperRoute
  '/metronome': typeof MetronomeRoute
  '/tuner': typeof TunerRoute
  '/worship-pad': typeof WorshipPadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/binaural-beats'
    | '/drum-looper'
    | '/metronome'
    | '/tuner'
    | '/worship-pad'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/binaural-beats'
    | '/drum-looper'
    | '/metronome'
    | '/tuner'
    | '/worship-pad'
  id:
    | '__root__'
    | '/'
    | '/binaural-beats'
    | '/drum-looper'
    | '/metronome'
    | '/tuner'
    | '/worship-pad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BinauralBeatsRoute: typeof BinauralBeatsRoute
  DrumLooperRoute: typeof DrumLooperRoute
  MetronomeRoute: typeof MetronomeRoute
  TunerRoute: typeof TunerRoute
  WorshipPadRoute: typeof WorshipPadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binaural-beats': {
      id: '/binaural-beats'
      path: '/binaural-beats'
      fullPath: '/binaural-beats'
      preLoaderRoute: typeof BinauralBeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drum-looper': {
      id: '/drum-looper'
      path: '/drum-looper'
      fullPath: '/drum-looper'
      preLoaderRoute: typeof DrumLooperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metronome': {
      id: '/metronome'
      path: '/metronome'
      fullPath: '/metronome'
      preLoaderRoute: typeof MetronomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuner': {
      id: '/tuner'
      path: '/tuner'
      fullPath: '/tuner'
      preLoaderRoute: typeof TunerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worship-pad': {
      id: '/worship-pad'
      path: '/worship-pad'
      fullPath: '/worship-pad'
      preLoaderRoute: typeof WorshipPadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BinauralBeatsRoute: BinauralBeatsRoute,
  DrumLooperRoute: DrumLooperRoute,
  MetronomeRoute: MetronomeRoute,
  TunerRoute: TunerRoute,
  WorshipPadRoute: WorshipPadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
