/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TunerRouteImport } from './routes/tuner'
import { Route as MetronomeRouteImport } from './routes/metronome'
import { Route as DrumLooperRouteImport } from './routes/drum-looper'
import { Route as IndexRouteImport } from './routes/index'

const TunerRoute = TunerRouteImport.update({
  id: '/tuner',
  path: '/tuner',
  getParentRoute: () => rootRouteImport,
} as any)
const MetronomeRoute = MetronomeRouteImport.update({
  id: '/metronome',
  path: '/metronome',
  getParentRoute: () => rootRouteImport,
} as any)
const DrumLooperRoute = DrumLooperRouteImport.update({
  id: '/drum-looper',
  path: '/drum-looper',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drum-looper': typeof DrumLooperRoute
  '/metronome': typeof MetronomeRoute
  '/tuner': typeof TunerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drum-looper': typeof DrumLooperRoute
  '/metronome': typeof MetronomeRoute
  '/tuner': typeof TunerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drum-looper': typeof DrumLooperRoute
  '/metronome': typeof MetronomeRoute
  '/tuner': typeof TunerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drum-looper' | '/metronome' | '/tuner'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drum-looper' | '/metronome' | '/tuner'
  id: '__root__' | '/' | '/drum-looper' | '/metronome' | '/tuner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrumLooperRoute: typeof DrumLooperRoute
  MetronomeRoute: typeof MetronomeRoute
  TunerRoute: typeof TunerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tuner': {
      id: '/tuner'
      path: '/tuner'
      fullPath: '/tuner'
      preLoaderRoute: typeof TunerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metronome': {
      id: '/metronome'
      path: '/metronome'
      fullPath: '/metronome'
      preLoaderRoute: typeof MetronomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drum-looper': {
      id: '/drum-looper'
      path: '/drum-looper'
      fullPath: '/drum-looper'
      preLoaderRoute: typeof DrumLooperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrumLooperRoute: DrumLooperRoute,
  MetronomeRoute: MetronomeRoute,
  TunerRoute: TunerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
